name: Second Workflow
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from the repo
        uses: actions/checkout@v5.0.0
      - name: install node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 20
      - name: get node version
        run: node --version
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
